let elAlert1 = alert("Assalomu alaykum, siz uchun maxsus blits savollar tayyorladim (oldingi oylarda o'tilgan mavzulardan), undan oldin siz haqizda bilmoqchi edim")
let elNews = prompt("Ismingizni kiriting")
let elNews2 = prompt("Yo'nalishingiz (Masalan: backend)")
let elNews3 = prompt("Yoshingizni kiriting")
let elNews4 = prompt("Qayerda tavallud topgansiz?")
let elAlert2 =alert ("Qani boshladik, Omad")
let elQ1 = prompt("HTML nima? ")
let elQ2 = prompt("Attributlar haqida nima bilasiz?")
let elQ3 = prompt("ol va ul ro'yhat element farqlari qanday?")
let elQ4 = prompt ("ALT attributi qaysi teg bilan va  nima uchun ishlatiladi ?")
let elQ5 = prompt ("HTMLga CSSni ulashning (qo'llashniing) qaysi yo'llarini bilasiz? ")
let elQ6 = prompt ("CSSda qanday positionlar mavjud (MISOL: fixed) va default qaysi birida bo'ladi ")
let elQ7 = prompt ("Qaysi HTMl tagi orqali CSSni internal ulashimiz mumkin?")
let elQ8 = prompt ("Paddingda manfiy qiymat ishlatish mumkinmi?")
let elQ9 = prompt ("scrset atributi qaysi teg bilan ishlaydi va unding foydasi qanday?")
let elQ10 = prompt ("CSS box model elementlari qaysilar?, ularni yozib qoldiring")
let elAlert3 = alert( "Rahmat, maqsadlaringiz sari harakatdan aslo to'xtamang!")

// let elNews5 = alert (elNews + " " + elNews2 + " " + elNews3 + " " + elNews4)
 console.log("1 " + elQ1 + " 2 " + elQ2 + " 3 " + elQ3 + " 4 " + elQ4 + " 5 " + elQ5 + " 6 " + elQ6 + " 7 " + elQ7 + " 8 " + elQ8 + " 9 " + elQ9 + " 10 " + elQ10 + " ");
